services:
  job-bot:
    build: .
    container_name: job_linkedin_bot
    # restart: always <- use se quiseres ter sinais a cada  segundo, irá rodar que nem servidor.
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["python","-u","bot.py"]

  web:
    build: .
    container_name: job_linkedin_web
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: ["python","-u","app.py"]
    restart: unless-stopped
